/**
 * FrameworkManager - 1-Click Starter Scaffolding for PHP Projects
 * Supports WordPress, Laravel, Vanilla PHP / Modern Dashboard, CodeIgniter
 */

const fs = require('fs');
const path = require('path');
const { spawn, exec } = require('child_process');

class FrameworkManager {
  constructor() {}

  /**
   * Scaffold a project based on framework type
   * @param {string} framework 'wordpress' | 'laravel' | 'vanilla' | 'codeigniter'
   * @param {string} targetDir Destination folder
   * @param {object} options Additional options (name, dbName, onProgress)
   */
  async scaffold(framework, targetDir, options = {}) {
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    const type = (framework || 'vanilla').toLowerCase();

    if (type === 'vanilla') {
      return this._scaffoldVanilla(targetDir, options);
    } else if (type === 'wordpress') {
      return this._scaffoldWordPress(targetDir, options);
    } else if (type === 'laravel') {
      return this._scaffoldLaravel(targetDir, options);
    } else if (type === 'codeigniter') {
      return this._scaffoldCodeIgniter(targetDir, options);
    } else {
      return this._scaffoldVanilla(targetDir, options);
    }
  }

  /**
   * Vanilla PHP Starter with modern responsive UI and DB status checker
   */
  async _scaffoldVanilla(targetDir, options) {
    const siteName = options.name || path.basename(targetDir);
    const dbName = options.dbName || '';

    const indexPhp = `<?php
/**
 * ${siteName} - Local Development Starter
 * Generated by Antigravity Localhost Panel
 */

$appName = '${siteName}';
$phpVersion = PHP_VERSION;
$serverSoftware = $_SERVER['SERVER_SOFTWARE'] ?? 'PHP Built-in Server';
$documentRoot = __DIR__;
$currentTime = date('Y-m-d H:i:s');

// Database Connection Test
$dbConnected = false;
$dbError = null;
$dbHost = '127.0.0.1';
$dbUser = 'root';
$dbPass = '';
$dbName = '${dbName}';

if (!empty($dbName)) {
    try {
        $pdo = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 2
        ]);
        $dbConnected = true;
    } catch (Exception $e) {
        $dbError = $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= htmlspecialchars($appName) ?> — Localhost</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg: #0b0b14;
      --card-bg: #141424;
      --border: #23233c;
      --accent: #6366f1;
      --accent-glow: rgba(99, 102, 241, 0.25);
      --green: #10b981;
      --red: #f43f5e;
      --text: #f8fafc;
      --text-muted: #94a3b8;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Plus Jakarta Sans', sans-serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 24px;
    }
    .container {
      max-width: 680px;
      width: 100%;
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 20px;
      padding: 40px;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5), 0 0 40px var(--accent-glow);
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 4px 12px;
      border-radius: 9999px;
      font-size: 12px;
      font-weight: 600;
      background: rgba(16, 185, 129, 0.15);
      color: var(--green);
      border: 1px solid rgba(16, 185, 129, 0.3);
      margin-bottom: 20px;
    }
    .badge-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--green); }
    h1 { font-size: 32px; font-weight: 800; letter-spacing: -0.5px; margin-bottom: 8px; }
    p.subtitle { color: var(--text-muted); font-size: 15px; margin-bottom: 32px; }
    .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 32px; }
    .stat-card {
      background: rgba(255, 255, 255, 0.03);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 16px;
    }
    .stat-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--text-muted); margin-bottom: 4px; font-weight: 600; }
    .stat-val { font-size: 15px; font-weight: 700; font-family: 'JetBrains Mono', monospace; color: #fff; }
    .actions { display: flex; gap: 12px; flex-wrap: wrap; }
    .btn {
      padding: 10px 20px;
      border-radius: 10px;
      font-size: 13px;
      font-weight: 600;
      text-decoration: none;
      display: inline-flex;
      align-items: center;
      gap: 8px;
      transition: all 0.2s;
    }
    .btn-primary { background: var(--accent); color: #fff; }
    .btn-primary:hover { opacity: 0.9; transform: translateY(-1px); }
    .btn-secondary { background: rgba(255,255,255,0.06); color: var(--text); border: 1px solid var(--border); }
    .btn-secondary:hover { background: rgba(255,255,255,0.1); }
    code { font-family: 'JetBrains Mono', monospace; font-size: 12px; background: rgba(0,0,0,0.3); padding: 2px 6px; border-radius: 4px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="badge">
      <span class="badge-dot"></span> Site Running Live
    </div>
    <h1><?= htmlspecialchars($appName) ?></h1>
    <p class="subtitle">Your local PHP environment is active and serving traffic smoothly.</p>

    <div class="grid">
      <div class="stat-card">
        <div class="stat-label">PHP Version</div>
        <div class="stat-val"><?= htmlspecialchars($phpVersion) ?></div>
      </div>
      <div class="stat-card">
        <div class="stat-label">MySQL Status</div>
        <div class="stat-val" style="color: <?= $dbConnected ? 'var(--green)' : 'var(--text-muted)' ?>">
          <?= $dbConnected ? 'Connected (' . htmlspecialchars($dbName) . ')' : (empty($dbName) ? 'Not configured' : 'Connection failed') ?>
        </div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Web Server</div>
        <div class="stat-val"><?= htmlspecialchars($serverSoftware) ?></div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Document Root</div>
        <div class="stat-val" style="font-size: 11px; word-break: break-all;"><?= htmlspecialchars($documentRoot) ?></div>
      </div>
    </div>

    <div class="actions">
      <a href="?phpinfo=1" class="btn btn-secondary">PHP Info</a>
      <a href="/api.php" class="btn btn-secondary">JSON API Test</a>
    </div>
  </div>
</body>
</html>
<?php
if (isset($_GET['phpinfo'])) {
    phpinfo();
    exit;
}
?>
`;

    const apiPhp = `<?php
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');

echo json_encode([
    'status' => 'success',
    'app' => '${siteName}',
    'php_version' => PHP_VERSION,
    'server_time' => date('c'),
    'message' => 'Antigravity Localhost API is functioning properly.'
], JSON_PRETTY_PRINT);
`;

    fs.writeFileSync(path.join(targetDir, 'index.php'), indexPhp, 'utf8');
    fs.writeFileSync(path.join(targetDir, 'api.php'), apiPhp, 'utf8');

    return {
      success: true,
      framework: 'vanilla',
      entryFile: 'index.php',
      message: 'Vanilla PHP starter created with index.php and api.php'
    };
  }

  /**
   * WordPress Starter Scaffolding
   */
  async _scaffoldWordPress(targetDir, options) {
    const siteName = options.name || path.basename(targetDir);
    const dbName = options.dbName || siteName.toLowerCase().replace(/[^a-z0-9_]/g, '_');

    // Create standard WordPress wp-config-sample and starter structure
    const indexPhp = `<?php
/**
 * Front to the WordPress application.
 */
define('WP_USE_THEMES', true);

// Check if WordPress core is installed
if (file_exists(__DIR__ . '/wp-blog-header.php')) {
    require __DIR__ . '/wp-blog-header.php';
} else {
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>WordPress Setup — ${siteName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif; background: #f0f0f1; color: #3c434a; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; }
    .wrap { background: #fff; padding: 40px; border-radius: 8px; max-width: 520px; box-shadow: 0 4px 15px rgba(0,0,0,0.08); text-align: center; }
    h1 { color: #1d2327; font-size: 24px; margin-bottom: 12px; }
    p { font-size: 14px; line-height: 1.6; color: #646970; }
    .btn { display: inline-block; background: #2271b1; color: #fff; text-decoration: none; padding: 10px 20px; border-radius: 4px; font-weight: 600; margin-top: 20px; font-size: 14px; }
    .btn:hover { background: #135e96; }
    .db-box { background: #f6f7f7; border: 1px solid #dcdcde; border-radius: 4px; padding: 12px; margin: 20px 0; font-family: monospace; font-size: 13px; text-align: left; }
  </style>
</head>
<body>
  <div class="wrap">
    <svg width="64" height="64" viewBox="0 0 100 100" style="margin-bottom:16px"><circle cx="50" cy="50" r="48" fill="#2271b1"/><path fill="#fff" d="M18.8 50c0 14.8 10.3 27.2 24.3 30.5L25.8 32.7C21.4 37.6 18.8 43.5 18.8 50zm49.9-1.9c0-5-1.8-8.5-3.3-11.2-2-3.4-3.9-6.3-3.9-9.7 0-3.8 2.9-7.3 6.9-7.3.2 0 .4 0 .6.1C62.6 15.6 53.6 13 43.7 13c-14.7 0-27.6 6.8-35.9 17.3l27.1 74.3 8.3-22.9-10.4-31.5c1.4-.1 2.7-.2 2.7-.2 1.3-.1 1.1-2-.2-2 0 0-3.9.3-6.4.3-2.4 0-6.3-.3-6.3-.3-1.3 0-1.4 1.9-.2 2 0 0 1.3.1 2.5.2l9.7 26.6-5.8 17.5C18.6 84.7 10 70.8 10 50c0-9.6 3.6-18.4 9.6-25.2L44.8 91c1.7.5 3.4.8 5.2.8 5.7 0 11.1-1.3 16-3.6L44.1 36.8l7.6-20.8c.8 0 1.6-.1 2.4-.1 8.8 0 16.9 3.5 22.9 9.3-.3.2-.5.5-.5.9 0 3.3 1.9 6.2 3.9 9.6 1.8 3.2 3.9 7.2 3.9 12.8 0 9.8-5.7 24.9-15.6 31.6z"/></svg>
    <h1>WordPress Ready for Setup</h1>
    <p>Database configured for this project:</p>
    <div class="db-box">
      Database: <strong>${dbName}</strong><br>
      Host: <strong>127.0.0.1:3306</strong><br>
      User: <strong>root</strong>
    </div>
    <p>You can run WordPress installer or download full WordPress core.</p>
    <a href="https://wordpress.org/download/" target="_blank" class="btn">Download WordPress Core</a>
  </div>
</body>
</html>
<?php
}
`;

    const wpConfig = `<?php
/**
 * WordPress local configuration
 */
define('DB_NAME', '${dbName}');
define('DB_USER', 'root');
define('DB_PASSWORD', '');
define('DB_HOST', '127.0.0.1:3306');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

define('AUTH_KEY',         'antigravity_local_dev_key_1');
define('SECURE_AUTH_KEY',  'antigravity_local_dev_key_2');
define('LOGGED_IN_KEY',    'antigravity_local_dev_key_3');
define('NONCE_KEY',        'antigravity_local_dev_key_4');

$table_prefix = 'wp_';
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}
if (file_exists(ABSPATH . 'wp-settings.php')) {
    require_once ABSPATH . 'wp-settings.php';
}
`;

    fs.writeFileSync(path.join(targetDir, 'index.php'), indexPhp, 'utf8');
    fs.writeFileSync(path.join(targetDir, 'wp-config-sample.php'), wpConfig, 'utf8');

    return {
      success: true,
      framework: 'wordpress',
      entryFile: 'index.php',
      dbName,
      message: `WordPress starter template ready with database "${dbName}" preset.`
    };
  }

  /**
   * Laravel Project Scaffolding
   */
  async _scaffoldLaravel(targetDir, options) {
    const siteName = options.name || path.basename(targetDir);
    const publicDir = path.join(targetDir, 'public');
    if (!fs.existsSync(publicDir)) {
      fs.mkdirSync(publicDir, { recursive: true });
    }

    const indexPhp = `<?php
use Illuminate\Contracts\Http\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

if (file_exists(__DIR__.'/../vendor/autoload.php')) {
    require __DIR__.'/../vendor/autoload.php';
    $app = require_once __DIR__.'/../bootstrap/app.php';
    $kernel = $app->make(Kernel::class);
    $response = $kernel->handle(
        $request = Request::capture()
    )->send();
    $kernel->terminate($request, $response);
} else {
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Laravel — ${siteName}</title>
  <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet" />
  <style>
    body { font-family: Figtree, sans-serif; background: #0f172a; color: #f8fafc; min-height: 100vh; display: flex; align-items: center; justify-content: center; margin: 0; }
    .card { background: #1e293b; border: 1px solid #334155; border-radius: 16px; padding: 40px; max-width: 580px; text-align: center; box-shadow: 0 20px 25px -5px rgba(0,0,0,0.3); }
    .logo { color: #f43f5e; font-size: 28px; font-weight: 800; margin-bottom: 12px; }
    p { color: #94a3b8; font-size: 15px; line-height: 1.6; }
    .cmd { background: #0b0f19; border: 1px solid #334155; border-radius: 8px; padding: 12px; font-family: monospace; font-size: 13px; color: #38bdf8; margin: 20px 0; text-align: left; }
  </style>
</head>
<body>
  <div class="card">
    <div class="logo">Laravel 11 Ready</div>
    <p>Your document root is set to <code>public/</code>. Run composer install to pull dependencies:</p>
    <div class="cmd">
      cd "${targetDir.replace(/\\/g, '/')}"<br>
      composer create-project laravel/laravel . --prefer-dist
    </div>
    <p style="font-size:12px;color:#64748b;">Antigravity Localhost Panel will auto-serve from <code>public/index.php</code></p>
  </div>
</body>
</html>
<?php
}
`;

    fs.writeFileSync(path.join(publicDir, 'index.php'), indexPhp, 'utf8');

    return {
      success: true,
      framework: 'laravel',
      entryFile: 'public/index.php',
      rootOverride: publicDir,
      message: 'Laravel project skeleton prepared with public/index.php routing.'
    };
  }

  /**
   * CodeIgniter 4 Scaffolding
   */
  async _scaffoldCodeIgniter(targetDir, options) {
    const publicDir = path.join(targetDir, 'public');
    if (!fs.existsSync(publicDir)) {
      fs.mkdirSync(publicDir, { recursive: true });
    }

    const indexPhp = `<?php
// CodeIgniter 4 Entry Point
if (file_exists(__DIR__ . '/../app/Config/Paths.php')) {
    define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);
    require __DIR__ . '/../app/Config/Paths.php';
    $paths = new Config\\Paths();
    require $paths->systemDirectory . '/Boot.php';
    exit(CodeIgniter\\Boot::bootWeb($paths));
} else {
    echo "<h1>CodeIgniter 4 Ready</h1><p>Run <code>composer create-project codeigniter4/appstarter .</code> in this directory.</p>";
}
`;
    fs.writeFileSync(path.join(publicDir, 'index.php'), indexPhp, 'utf8');

    return {
      success: true,
      framework: 'codeigniter',
      entryFile: 'public/index.php',
      rootOverride: publicDir,
      message: 'CodeIgniter 4 starter skeleton created.'
    };
  }
}

module.exports = FrameworkManager;
